apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # base64 de "tpavancee"
  POSTGRES_USER: dHBhdmFuY2Vl
  POSTGRES_PASSWORD: dHBhdmFuY2Vl
  # base64 de "MasterAnnonce"
  POSTGRES_DB: TWFzdGVyQW5ub25jZQ==
